//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizzApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopTen
    {
        public int Id { get; set; }
        public string NickName { get; set; }
        public int Points { get; set; }
    }
}
