//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace QuizzApp.Models
{
    public partial class Answer
    {
        public long AnswerId { get; set; }
        public long QuestionId { get; set; }
        public string Value { get; set; }
        public bool Correct { get; set; }

        public virtual Question Questions { get; set; }
    }
}