//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizzApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int IdAnswer { get; set; }
        public int IdQuestion { get; set; }
        public string Text { get; set; }
        public bool Value { get; set; }
    
        public virtual Question Questions { get; set; }
    }
}
